name: Docker Image CI

on:
  push:
    branches-ignore: [ "master" ]
  pull_request:
    branches-ignore: [ "master" ]
    tags-ignore : 
      - "*"
      - "*/*"
      - "**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test build to docker image
      run: docker build . --file Dockerfile --tag buildimage:$(date +%s)
