name: Production GHCR

on:
  push:
  tags:
    - '*'
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login_build_push_registry
      run: |
        docker login --username unseensenpai --password ${{ secrets.GH_PAT }} ghcr.io
        docker build --tag ghcr.io/unseensenpai/restapiproject-ghcr:latest --file Dockerfile .
        docker push ghcr.io/unseensenpai/restapiproject-ghcr:latest
