name: Docker Image CI for GHCR

on:
  push:
      tags:
         - '*'
jobs:
  production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy_production
      run: |
        docker login --username unseensenpai --password ${{ secrets.GH_PAT }} ghcr.io
        docker build --tag ghcr.io/unseensenpai/restapiproject-ghcr:latest --file Dockerfile .
        docker push ghcr.io/unseensenpai/restapiproject-ghcr:latest
